### ISSUE TITLE
Update README with BSI Bump Instructions

### ISSUE THREAD

**Issue by dmackenz** [Brightspace/brightspace-integration#1814]
Could someone create a guide in the README on how to bump BSI, similar to how there is one for unbundling BSI?

**Comment by dlockhart** [comment]
Beyond what's in the [Tagging & Publishing](https://github.com/Brightspace/brightspace-integration#tagging--publishing) and [Updating LP to reference new BSI](https://github.com/Brightspace/brightspace-integration#updating-lp-to-reference-the-new-version-of-bsi) sections?

Essentially everything is automated now, so there's really nothing you need to do to "bump BSI" (unless you're in a release branch).
