### ISSUE TITLE
Move peter-evans/repository-dispatch to third-party-actions (when we're satisfied with it)

### ISSUE THREAD

**Issue by j3parker** [Brightspace/brightspace-integration#2248]
https://github.com/Brightspace/brightspace-integration/blob/c9fc0172b368e7050693395f72aba2b205d23721/.github/workflows/trigger-lms-sync.yml#L34-L35

**Comment by svanherk** [comment]
Gonna close this issue - seems like it was resolved by https://github.com/Brightspace/brightspace-integration/pull/2264 which removed this action altogether
