### ISSUE TITLE
copy feature should be an action on the source target, not it's parent

### ISSUE THREAD

**Issue by letzfets** [Brightspace/brightspace-integration#3130]
Example: copying a topic in a discussion forum: the copy option should be in the drop-down of the source (the element to be copied), not in the parent (i.e. the forum under more actions, where it's now).
Filling in the source information in the copy form sheet is ridiculous and all against single source of information principle!

**Comment by letzfets** [comment]
as a feature request: should be possible to copy by drag-and-drop, while pressing the alt-key. This should work on ANY element, that can be copied!

**Comment by cbellini** [comment]
Thank you for suggesting this feature! This would help improve the experience of managing content and I've raised it with our product team.

However, this repository is not where that improvement will be worked on. I humbly request that you [create a new idea](https://desire2learn.brightidea.com/ideas/submit) in our [Product Idea Exchange](https://desire2learn.brightidea.com/ideas/boards) to ensure that your idea receives maximum visibility and also allows you to follow its progress.

**Comment by letzfets** [comment]
😱 OMG, that explains why my brain is refusing to click the millions of clicks in your software.

But sure, if this is considered "intended behavior", it definitely cannot be an issue in here. I'll ask in the PIE   for this normal behavior.

Thanks for your fast reply. 🙏🙏 Highly appreciated.
