### ISSUE TITLE
Remove resolution for d2l-offscreen

### ISSUE THREAD

**Issue by dlockhart** [Brightspace/brightspace-integration#738]
We currently require a forced resolution for `d2l-offscreen` because `vui-dropdown` is using version `2.1.0`. It needs to be upgraded to the latest `d2l-offscreen` and re-released.

**Comment by jwong-d2l** [comment]
are these close-able then?

**Comment by svanherk** [comment]
> are these close-able then?

Yeah, these no longer make sense.  All the old `vui` repos used by BSI were just copied to here, and we no longer use `bower` and `resolutions`.  Time flies! 😝
